// <auto-generated />
using ApiAnimalesEtsotikos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiAnimalesEtsotikos.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20231128154138_agf")]
    partial class agf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiAnimalesEtsotikos.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Altura")
                        .HasColumnType("real");

                    b.Property<string>("Enfermedad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCientifico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisOrigen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.Property<string>("Propietario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Animal");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Altura = 2.4f,
                            Enfermedad = "tos",
                            Img = "https://as01.epimg.net/diarioas/imagenes/2022/05/29/actualidad/1653826510_995351_1653826595_noticia_normal_recorte1.jpg",
                            Nombre = "perro",
                            NombreCientifico = "pipi",
                            PaisOrigen = "Norteamérica del Sur",
                            Peso = 22f,
                            Propietario = "",
                            Status = 1
                        });
                });

            modelBuilder.Entity("ApiAnimalesEtsotikos.Models.Cliente", b =>
                {
                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cedula");

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            Cedula = "123",
                            Direccion = "Conocoto",
                            Nombre = "Edwing",
                            Password = "123"
                        });
                });

            modelBuilder.Entity("ApiAnimalesEtsotikos.Models.Veterinario", b =>
                {
                    b.Property<string>("NombreVeterinario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DireccionVeterinario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TelefonoVeterinario")
                        .HasColumnType("int");

                    b.HasKey("NombreVeterinario");

                    b.ToTable("Veterinario");

                    b.HasData(
                        new
                        {
                            NombreVeterinario = "Patitas del Saber",
                            DireccionVeterinario = "cuba",
                            TelefonoVeterinario = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
